export const state = {
    CENTER: [8.836955, -82.423918],
    ZOOM: 17,
    EARTH_RADIUS_KM: 6371,

    waypoints: [],
    polyline: null,
    markers: [],
    movingMarker: null,
    animationId: null,
    isPlaying: false,
    isPaused: false,
    _currentSpeedKmh: 0,
    lastFrameTimestamp: 0,
    totalDistanceKm: 0,
    traveledDistanceKm: 0,
    simElapsedSeconds: 0,
    followMode: true,
    isAtEnd: false,
    alarmTriggered: false,

    ALARM_TIMES: [
        { h: 16, m: 39, label: 'First 112 call' },
        { h: 16, m: 51, label: 'Second 112 call' },
    ],
    _112Fired: {},
    _112Points: [],
    _112PointMarkers: [],
    _prevSimSec: -1,
    _smoothViewDir: 0,
    _slopeDeg: 0,

    scheduledStops: [],
    scheduledStopMarkers: [],
    isAddingStops: false,
    stopRemaining: 0,
    activeStopIndex: -1,

    speedPoints: [],
    speedPointMarkers: [],
    isAddingSpeedPoints: false,

    customPoints: [],
    customPointMarkers: [],
    isAddingCustomPoints: false,

    batteryDrainLine: null,
    _drainStopDots: [],
    _drainStopActive: false,
    batteryDrainActive: false,
    _drainStartDist: 0,
    _drainStartSet: false,
    _drainEndDist: 0,
    _drainLastWpIdx: -1,
    _drainLastUpdateDist: 0,
    _drainEnded: false,
    _drainRepeat: null,

    routeElevationData: [],
    elevationHistory: [],
    _lastRecordedMinute: -1,

    _isZooming: false,
    currentLayer: null,

    map3d: null,
    _map3dPhotoMarkers: [],
    _map3dPoiMarkers: [],
    _map3dStopLabels: [],
    _map3dSpeedLabels: [],
    _map3dCustomLabels: [],
    _map3d112Labels: [],
    _alarmTimeouts: [],
};
